# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Blog
tagline:          'HTML5 blog FMAT'
url:              http://turnt-wookie.github.io/html5
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/turnt-wookie
